

```{r}

library("praatpicture")

```

```{r}
#Hungarian AND sentences
praatpicture("NOT_elephant_and_dog.wav",
             frames = c('sound', 'pitch', "TextGrid"),
             tg_file = "NOT_elephant_and_dog.TextGrid",
             ps = 14)
praatpicture("NOT_elephant_AAND_dog.wav",
             frames = c('sound', 'pitch', "TextGrid"),
             tg_file = "NOT_elephant_AAND_dog.TextGrid")
praatpicture("NOT_elephant_AND_dog2.wav",
             frames = c('sound', 'pitch', "TextGrid"),
             tg_file = "NOT_elephant_AND_dog2.TextGrid")

```


```{r}
#Hungarian OR sentences
praatpicture("NOT_elephant_or_dog.wav",
             frames = c('sound', 'pitch', "TextGrid"),
             tg_file = "NOT_elephant_or_dog.TextGrid",
             ps = 14)
praatpicture("NOT_elephant_OR_dog2.wav",
             frames = c('sound', 'pitch', "TextGrid"),
             tg_file = "NOT_elephant_OR_dog2.TextGrid")

```
```{r}
#English AND sentences
praatpicture("the_card_does_NOT_have_an_elephant_and_a_dog (2).wav",
             frames = c('sound', 'pitch', "TextGrid"),
             tg_file = "the_card_does_NOT_have_an_elephant_and_a_dog__2_.TextGrid",
             ps = 14)
praatpicture("the_card_does_not_have_an_elephant_AND_a_dog.wav",
             frames = c('sound', 'pitch', "TextGrid"),
             tg_file = "the_card_does_not_have_an_elephant_AND_a_dog.TextGrid")
```


```{r}
#English OR sentences
praatpicture("the_card_does_NOT_have_an_elephant_or_a_dog (2).wav",
             frames = c('sound', 'pitch', "TextGrid"),
             tg_file = "the_card_does_NOT_have_an_elephant_or_a_dog__2_.TextGrid",
             ps = 14)
praatpicture("the_card_does_not_have_an_elephant_or_a_dog.wav",
             frames = c('sound', 'pitch', "TextGrid"),
             tg_file = "the_card_does_not_have_an_elephant_or_a_dog.TextGrid")
```















